{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nebulaio.fullname" . }}
  labels:
    {{- include "nebulaio.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.s3.host }}
    - host: {{ .Values.ingress.s3.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.s3.path }}
            pathType: {{ .Values.ingress.s3.pathType }}
            backend:
              service:
                name: {{ include "nebulaio.fullname" . }}
                port:
                  name: s3
    {{- end }}
    {{- if .Values.ingress.admin.host }}
    - host: {{ .Values.ingress.admin.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.admin.path }}
            pathType: {{ .Values.ingress.admin.pathType }}
            backend:
              service:
                name: {{ include "nebulaio.fullname" . }}
                port:
                  name: admin
    {{- end }}
    {{- if .Values.ingress.console.host }}
    - host: {{ .Values.ingress.console.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.console.path }}
            pathType: {{ .Values.ingress.console.pathType }}
            backend:
              service:
                name: {{ include "nebulaio.fullname" . }}
                port:
                  name: console
    {{- end }}
{{- end }}
