{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulaio.fullname" . }}
  labels:
    {{- include "nebulaio.labels" . | nindent 4 }}
type: Opaque
data:
  root-user: {{ .Values.auth.rootUser | b64enc | quote }}
  root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- if .Values.auth.jwtSecret }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- end }}
{{- end }}
